import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { test } from "node:test";

const scripts = dirname(fileURLToPath(import.meta.url));
const begin = "<!-- BEGIN MOD TABLE (generated by lopari.app: pixi run update-metadata) -->";
const end = "<!-- END MOD TABLE -->";
const recentBegin = "<!-- BEGIN NEW ADDITIONS (generated by lopari.app: pixi run update-metadata) -->";
const recentEnd = "<!-- END NEW ADDITIONS -->";
const updatedBegin = "<!-- BEGIN RECENT UPDATES (generated by lopari.app: pixi run update-metadata) -->";
const updatedEnd = "<!-- END RECENT UPDATES -->";
const countBegin = "<!-- BEGIN MOD COUNT -->";
const countEnd = "<!-- END MOD COUNT -->";
const between = (output, from, to) => output.slice(output.indexOf(from) + from.length, output.indexOf(to)).trim();
const recentList = (output) => between(output, recentBegin, recentEnd);
const updatedList = (output) => between(output, updatedBegin, updatedEnd);
const readme = `Handwritten introduction with ${countBegin}0${countEnd} mods\n${recentBegin}\nold list\n${recentEnd}\nHandwritten middle\n${updatedBegin}\nold updates\n${updatedEnd}\n${begin}\nold table\n${end}\nHandwritten footer\n`;
const wobbly = {
  id: "wobbly-life", display_name: "Wobbly Life", repo: "itsloopyo/wobbly-life-headtracking",
  public: true, released: false, added: "2026-05-28", install_strategy: "BepInEx5",
  verified_sources: ["Steam", "Xbox"],
  game: { steam_app_id: 1211020, executable_relpath: "Wobbly Life.exe" },
  known_issues: ["Not comprehensively tested."],
  distribution: { type: "dev-release", pinned: {
    version: "0.0.0-nightly.old", built_at: "2026-09-01T00:00:00Z",
    zip_filename: "WobblyLifeHeadTracking-dev-installer.zip",
    download_url: "https://github.com/itsloopyo/wobbly-life-headtracking/releases/download/dev/WobblyLifeHeadTracking-dev-installer.zip",
  } },
};

const staleRelease = {
  pinned: {
    version: "1.0.0", tag_name: "v1.0.0",
    zip_filename: "WobblyLifeHeadTracking-installer.zip",
    download_url: "https://github.com/itsloopyo/wobbly-life-headtracking/releases/download/v1.0.0/WobblyLifeHeadTracking-installer.zip",
  },
  versions: [{ version: "1.0.0", tag_name: "v1.0.0" }],
};

function workspace(t, mods) {
  const root = mkdtempSync(join(tmpdir(), "lopari-catalog-test-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const site = join(root, "lopari.app");
  mkdirSync(join(site, "scripts"), { recursive: true });
  mkdirSync(join(root, "lopari", "catalog"), { recursive: true });
  mkdirSync(join(root, "itsloopyo"));
  for (const script of ["update-metadata.mjs", "generate-readme.mjs", "generate-feed.mjs"]) {
    copyFileSync(join(scripts, script), join(site, "scripts", script));
  }
  const catalog = { schema_version: 2, mods, native_games: [] };
  writeFileSync(join(site, "mods.json"), JSON.stringify(catalog));
  writeFileSync(join(root, "lopari", "catalog", "mods.json"), JSON.stringify(catalog));
  writeFileSync(join(root, "itsloopyo", "README.md"), readme);
  return {
    root, site,
    readmePath: join(root, "itsloopyo", "README.md"),
    feedPath: join(site, "feed.xml"),
  };
}

// The date is generate-readme's requirement, but that script runs after
// update-metadata has pinned every mod and rewritten both catalogs, so a new
// entry missing it used to fail the run at the far end with the files already
// written. Checked up front instead, before any GitHub call.
test("update-metadata refuses a public mod with no added date before it fetches anything", (t) => {
  const { root, site } = workspace(t, [{ ...wobbly, id: "undated", added: undefined }]);
  const sourcePath = join(root, "lopari", "catalog", "mods.json");
  const before = readFileSync(sourcePath, "utf8");
  const mock = join(root, "github.mjs");
  writeFileSync(mock, "globalThis.fetch = async (url) => { throw new Error('Unexpected fetch: ' + url); };");
  const result = spawnSync(process.execPath, ["--import", pathToFileURL(mock).href, join(site, "scripts", "update-metadata.mjs")], {
    encoding: "utf8", env: { ...process.env, GITHUB_TOKEN: "test-only" },
  });
  assert.equal(result.status, 1, result.stdout + result.stderr);
  assert.match(result.stderr, /public with no valid "added" date .*: undated/);
  assert.doesNotMatch(result.stderr, /Unexpected fetch/);
  assert.equal(readFileSync(sourcePath, "utf8"), before);
});

test("README lists verified stores without inferring support from detection", (t) => {
  const mods = [
    wobbly,
    { ...wobbly, id: "steam", display_name: "Steam only", verified_sources: ["Steam"],
      game: { gog_ids: ["123"], xbox_paths: ["example"] } },
    { ...wobbly, id: "labels", display_name: "Store labels",
      verified_sources: ["Gog", "Epic", "Msix", "Ea", "Ubisoft", "Manual"] },
    { ...wobbly, id: "empty", display_name: "Empty stores", verified_sources: [] },
    { ...wobbly, id: "absent", display_name: "Absent stores", verified_sources: undefined },
    { ...wobbly, id: "private", display_name: "Private mod", public: false },
    { ...wobbly, id: "external", display_name: "External mod", install_strategy: "External",
      release: { versions: [{ version: "1.2.3", published_at: "2026-09-02T00:00:00Z" }] } },
  ];
  const { site, readmePath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  const output = readFileSync(readmePath, "utf8");
  assert.ok(output.startsWith(`Handwritten introduction with ${countBegin}6${countEnd} mods\n${recentBegin}\n`));
  assert.ok(output.includes(`${recentEnd}\nHandwritten middle\n${updatedBegin}\n`));
  assert.ok(output.includes(`${updatedEnd}\n${begin}\n`));
  assert.ok(output.endsWith(`${end}\nHandwritten footer\n`));
  assert.ok(output.includes("| Game | Status | Supported stores | Links | Latest release |"));
  assert.ok(output.includes("| Wobbly Life | Beta | Steam, Xbox | [GitHub](https://github.com/itsloopyo/wobbly-life-headtracking) | dev build (2026-09-01) |"));
  assert.ok(output.includes("| External mod | Released | Steam, Xbox | [GitHub](https://github.com/itsloopyo/wobbly-life-headtracking) | v1.2.3 (2026-09-02) |"));
  assert.ok(output.includes("| Steam only | Beta | Steam |"));
  assert.ok(output.includes("| Store labels | Beta | GOG, Epic, Microsoft Store, EA app, Ubisoft Connect, Retail |"));
  assert.ok(output.includes("| Empty stores | Beta | Not specified |"));
  assert.ok(output.includes("| Absent stores | Beta | Not specified |"));
  assert.ok(output.includes("| External mod | Released | Steam, Xbox |"));
  assert.ok(!output.includes("Private mod"));
  for (const row of output.split("\n").filter(line => line.startsWith("|"))) {
    assert.equal(row.split("|").length, 7);
  }
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  assert.equal(readFileSync(readmePath, "utf8"), output);
});

const devBuilt = (builtAt) => ({ distribution: { ...wobbly.distribution, pinned: { ...wobbly.distribution.pinned, built_at: builtAt } } });

test("README lists the ten newest mods, newest first, ties by name", (t) => {
  const mods = [
    ...Array.from({ length: 9 }, (_, i) => ({
      ...wobbly, id: `new-${i}`, display_name: `New ${i}`, added: `2026-08-1${i}`,
    })),
    { ...wobbly, id: "tie-b", display_name: "Tie B", added: "2026-08-01" },
    { ...wobbly, id: "tie-a", display_name: "Tie A", added: "2026-08-01" },
    { ...wobbly, id: "private", display_name: "Private mod", public: false, added: "2026-09-30" },
  ];
  const { site, readmePath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  const repo = "[GitHub](https://github.com/itsloopyo/wobbly-life-headtracking)";
  const list = recentList(readFileSync(readmePath, "utf8")).split("\n");
  assert.equal(list.length, 10);
  assert.equal(list[0], `- **New 8** (Beta), added 2026-08-18 · ${repo}`);
  assert.equal(list[8], `- **New 0** (Beta), added 2026-08-10 · ${repo}`);
  assert.equal(list[9], `- **Tie A** (Beta), added 2026-08-01 · ${repo}`);
});

test("README lists a store a mod gained later as a platform release among the new games", (t) => {
  const mods = [
    { ...wobbly, verified_sources: ["Steam", "Xbox", "Msix"],
      source_added: { Xbox: "2026-09-11", Msix: "2026-09-13" } },
    { ...wobbly, id: "alpha", display_name: "Alpha", added: "2026-09-12" },
    { ...wobbly, id: "zed", display_name: "Zed", added: "2026-09-11" },
  ];
  const { site, readmePath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  const repo = "[GitHub](https://github.com/itsloopyo/wobbly-life-headtracking)";
  const output = readFileSync(readmePath, "utf8");
  assert.deepEqual(recentList(output).split("\n"), [
    `- **Wobbly Life** (Beta), Microsoft Store support added 2026-09-13 · ${repo}`,
    `- **Alpha** (Beta), added 2026-09-12 · ${repo}`,
    `- **Wobbly Life** (Beta), Xbox support added 2026-09-11 · ${repo}`,
    `- **Zed** (Beta), added 2026-09-11 · ${repo}`,
    `- **Wobbly Life** (Beta), added 2026-05-28 · ${repo}`,
  ]);
  assert.equal(updatedList(output), "No updates yet.");
});

test("README rejects a platform release on an unknown store without changing the file", (t) => {
  const { site, readmePath } = workspace(t, [{ ...wobbly, source_added: { Typo: "2026-09-11" } }]);
  const result = spawnSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")], { encoding: "utf8" });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /unknown verified source: Typo/);
  assert.equal(readFileSync(readmePath, "utf8"), readme);
});

test("README lists the ten latest builds of mods outside the new list, skipping launch-day builds", (t) => {
  const mods = [
    ...Array.from({ length: 10 }, (_, i) => ({
      ...wobbly, id: `new-${i}`, display_name: `New ${i}`, added: "2026-09-20",
      ...devBuilt("2026-09-25T00:00:00Z"),
    })),
    ...Array.from({ length: 9 }, (_, i) => ({
      ...wobbly, id: `dev-${i}`, display_name: `Dev ${i}`, added: "2026-01-01",
      ...devBuilt(`2026-09-0${i + 1}T00:00:00Z`),
    })),
    { ...wobbly, id: "stable", display_name: "Stable", added: "2026-01-01", released: true,
      release: { pinned: { version: "1.2.0", published_at: "2026-09-10T12:00:00Z" } } },
    { ...wobbly, id: "launch", display_name: "Launch day", added: "2026-09-15",
      ...devBuilt("2026-09-15T23:00:00Z") },
    { ...wobbly, id: "oldest", display_name: "Oldest", added: "2026-01-01",
      ...devBuilt("2026-08-01T00:00:00Z") },
  ];
  const { site, readmePath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  const repo = "[GitHub](https://github.com/itsloopyo/wobbly-life-headtracking)";
  const list = updatedList(readFileSync(readmePath, "utf8")).split("\n");
  assert.equal(list.length, 10);
  assert.equal(list[0], `- **Stable** (Released), v1.2.0 on 2026-09-10 · ${repo}`);
  assert.equal(list[1], `- **Dev 8** (Beta), dev build on 2026-09-09 · ${repo}`);
  assert.equal(list[9], `- **Dev 0** (Beta), dev build on 2026-09-01 · ${repo}`);
});

test("README says so when no mod has been updated since it was added", (t) => {
  const { site, readmePath } = workspace(t, [{ ...wobbly, added: "2026-09-01" }]);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  assert.equal(updatedList(readFileSync(readmePath, "utf8")), "No updates yet.");
});

test("README and feed refuse a public mod with no added date", (t) => {
  const { added: _, ...undated } = wobbly;
  const { site, readmePath, feedPath } = workspace(t, [undated]);
  for (const script of ["generate-readme.mjs", "generate-feed.mjs"]) {
    const result = spawnSync(process.execPath, [join(site, "scripts", script)], { encoding: "utf8" });
    assert.equal(result.status, 1, script);
    assert.match(result.stderr, /wobbly-life is public with no "added" date/);
  }
  assert.equal(readFileSync(readmePath, "utf8"), readme);
  assert.ok(!existsSync(feedPath));
});

test("feed lists public mods newest first and is stable across runs", (t) => {
  const mods = [
    wobbly,
    { ...wobbly, id: "newer", display_name: "Tom & Jerry <Deluxe>", added: "2026-09-19",
      description: "Works with any OpenTrack compatible tracker." },
    { ...wobbly, id: "private", display_name: "Private mod", public: false, added: "2026-09-30" },
  ];
  const { site, feedPath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-feed.mjs")]);
  const feed = readFileSync(feedPath, "utf8");
  assert.ok(feed.includes("<updated>2026-09-19T00:00:00Z</updated>\n  <entry>"));
  assert.ok(feed.indexOf("mod/newer") < feed.indexOf("mod/wobbly-life"));
  assert.ok(feed.includes("<title>Tom &amp; Jerry &lt;Deluxe&gt;</title>"));
  assert.ok(feed.includes("<summary>Works with any OpenTrack compatible tracker.</summary>"));
  assert.ok(feed.includes("<published>2026-05-28T00:00:00Z</published>"));
  assert.ok(!feed.includes("Private mod"));
  assert.equal(feed.match(/<entry>/g).length, 2);
  execFileSync(process.execPath, [join(site, "scripts", "generate-feed.mjs")]);
  assert.equal(readFileSync(feedPath, "utf8"), feed);
});

test("README rejects an unknown store without changing the file", (t) => {
  const { site, readmePath } = workspace(t, [{ ...wobbly, verified_sources: ["Typo"] }]);
  const result = spawnSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")], { encoding: "utf8" });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /unknown verified source: Typo/);
  assert.equal(readFileSync(readmePath, "utf8"), readme);
});

for (const live of [false, true]) {
  for (const scenario of [
    { name: "drops a stale release on an unstamped entry", released: false, dev: "available", dropRelease: true, status: 0 },
    { name: "drops a stale release and unstamps an entry with a dev build", released: true, dev: "available", dropRelease: true, status: 0 },
    { name: "preserves a stale release and errors without a dev channel", released: true, dev: "none", status: 1 },
    { name: "preserves a stale release and errors when the dev release is missing", released: true, dev: "missing", status: 1 },
    { name: "preserves a stale release and errors when the dev installer is missing", released: true, dev: "assetless", status: 1 },
    { name: "preserves the stable release and stamp on a GitHub failure", released: true, dev: "available", releaseFailure: true, status: 1 },
  ]) {
    test(`metadata refresh ${scenario.name} (${live ? "live" : "full"})`, (t) => {
      const mod = { ...wobbly, released: scenario.released, release: staleRelease };
      if (scenario.dev === "none") delete mod.distribution;
      const expected = structuredClone(mod);
      if (scenario.dropRelease) {
        delete expected.release;
        expected.released = false;
      }
      if (["missing", "assetless"].includes(scenario.dev)) delete expected.distribution.pinned;
      const { root, site } = workspace(t, [mod]);
      const sourcePath = join(root, "lopari", "catalog", "mods.json");
      const originalSource = readFileSync(sourcePath, "utf8");
      const mock = join(root, "github.mjs");
      writeFileSync(mock, `
const scenario = ${JSON.stringify(scenario)};
const pin = ${JSON.stringify(wobbly.distribution.pinned)};
globalThis.fetch = async (url) => {
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases?per_page=25') {
    return scenario.releaseFailure
      ? new Response('unavailable', { status: 503, statusText: 'Service Unavailable' })
      : Response.json([]);
  }
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases/tags/dev' && scenario.dev !== 'none') {
    if (scenario.dev === 'missing') return new Response(null, { status: 404 });
    return Response.json({
      name: 'Development build ' + pin.version, tag_name: 'dev', prerelease: true,
      published_at: pin.built_at,
      assets: scenario.dev === 'assetless' ? [] : [{ name: pin.zip_filename, browser_download_url: pin.download_url }],
    });
  }
  if (url === 'https://api.github.com/repos/itsloopyo/lopari-releases/releases/latest') return Response.json({tag_name: 'v0.8.3', assets: []});
  throw new Error('Unexpected fetch: ' + url);
};
`);
      const result = spawnSync(process.execPath, ["--import", pathToFileURL(mock).href, join(site, "scripts", "update-metadata.mjs"), ...(live ? ["--live"] : [])], {
        encoding: "utf8", env: { ...process.env, GITHUB_TOKEN: "test-only" },
      });
      assert.equal(result.status, scenario.status, result.stdout + result.stderr);
      if (scenario.releaseFailure) {
        assert.match(result.stderr, /GET https:\/\/api\.github\.com\/repos\/itsloopyo\/wobbly-life-headtracking\/releases\?per_page=25 -> 503 Service Unavailable/);
        assert.doesNotMatch(result.stderr, /has no dev build to fall back on/);
      } else if (scenario.status === 1) {
        assert.match(result.stderr, /has no dev build to fall back on\. Restore the release, or hand-edit the entry in the lopari catalog/);
      } else {
        assert.equal(result.stderr, "");
      }
      const output = JSON.parse(readFileSync(join(site, "mods.json"), "utf8"));
      assert.deepEqual(output.mods, [expected]);
      if (live) assert.equal(readFileSync(sourcePath, "utf8"), originalSource);
      else assert.deepEqual(JSON.parse(readFileSync(sourcePath, "utf8")), output);
    });
  }

  test(`metadata refresh preserves Wobbly's stores and shared package (${live ? "live" : "full"})`, (t) => {
    const { root, site } = workspace(t, [wobbly]);
    const sourcePath = join(root, "lopari", "catalog", "mods.json");
    const originalSource = readFileSync(sourcePath, "utf8");
    const mock = join(root, "github.mjs");
    writeFileSync(mock, `
const release = ${JSON.stringify({
  name: "Development build 0.0.0-nightly.20260911.0a3073b", tag_name: "dev", prerelease: true,
  published_at: "2026-09-11T19:35:57Z",
  assets: [{ name: wobbly.distribution.pinned.zip_filename, browser_download_url: wobbly.distribution.pinned.download_url }],
})};
globalThis.fetch = async (url) => {
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases?per_page=25') return Response.json([release]);
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases/tags/dev') return Response.json(release);
  if (url === 'https://api.github.com/repos/itsloopyo/lopari-releases/releases/latest') return Response.json({tag_name: 'v0.8.3', assets: []});
  throw new Error('Unexpected fetch: ' + url);
};
`);
    execFileSync(process.execPath, ["--import", pathToFileURL(mock).href, join(site, "scripts", "update-metadata.mjs"), ...(live ? ["--live"] : [])], {
      env: { ...process.env, GITHUB_TOKEN: "test-only" },
    });
    const output = JSON.parse(readFileSync(join(site, "mods.json"), "utf8"));
    const updated = output.mods[0];
    assert.deepEqual(updated, {
      ...wobbly, distribution: { ...wobbly.distribution, pinned: {
        ...wobbly.distribution.pinned,
        version: "0.0.0-nightly.20260911.0a3073b", built_at: "2026-09-11T19:35:57Z",
      } },
    });
    assert.equal(output.schema_version, 2);
    if (live) assert.equal(readFileSync(sourcePath, "utf8"), originalSource);
    else assert.deepEqual(JSON.parse(readFileSync(sourcePath, "utf8")), output);
  });
}
