import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { test } from "node:test";

const scripts = dirname(fileURLToPath(import.meta.url));
const begin = "<!-- BEGIN MOD TABLE (generated by lopari.app: pixi run update-metadata) -->";
const end = "<!-- END MOD TABLE -->";
const readme = `Handwritten introduction\n${begin}\nold table\n${end}\nHandwritten footer\n`;
const wobbly = {
  id: "wobbly-life", display_name: "Wobbly Life", repo: "itsloopyo/wobbly-life-headtracking",
  public: true, released: false, install_strategy: "BepInEx5",
  verified_sources: ["Steam", "Xbox"],
  game: { steam_app_id: 1211020, executable_relpath: "Wobbly Life.exe" },
  known_issues: ["Not comprehensively tested."],
  distribution: { type: "dev-release", pinned: {
    version: "0.0.0-nightly.old", built_at: "2026-09-01T00:00:00Z",
    zip_filename: "WobblyLifeHeadTracking-dev-installer.zip",
    download_url: "https://github.com/itsloopyo/wobbly-life-headtracking/releases/download/dev/WobblyLifeHeadTracking-dev-installer.zip",
  } },
};

function workspace(t, mods) {
  const root = mkdtempSync(join(tmpdir(), "lopari-catalog-test-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const site = join(root, "lopari.app");
  mkdirSync(join(site, "scripts"), { recursive: true });
  mkdirSync(join(root, "lopari", "catalog"), { recursive: true });
  mkdirSync(join(root, "itsloopyo"));
  for (const script of ["update-metadata.mjs", "generate-readme.mjs"]) {
    copyFileSync(join(scripts, script), join(site, "scripts", script));
  }
  const catalog = { schema_version: 2, mods, native_games: [] };
  writeFileSync(join(site, "mods.json"), JSON.stringify(catalog));
  writeFileSync(join(root, "lopari", "catalog", "mods.json"), JSON.stringify(catalog));
  writeFileSync(join(root, "itsloopyo", "README.md"), readme);
  return { root, site, readmePath: join(root, "itsloopyo", "README.md") };
}

test("README lists verified stores without inferring support from detection", (t) => {
  const mods = [
    wobbly,
    { ...wobbly, id: "steam", display_name: "Steam only", verified_sources: ["Steam"],
      game: { gog_ids: ["123"], xbox_paths: ["example"] } },
    { ...wobbly, id: "labels", display_name: "Store labels",
      verified_sources: ["Gog", "Epic", "Msix", "Ea", "Ubisoft", "Manual"] },
    { ...wobbly, id: "empty", display_name: "Empty stores", verified_sources: [] },
    { ...wobbly, id: "absent", display_name: "Absent stores", verified_sources: undefined },
    { ...wobbly, id: "private", display_name: "Private mod", public: false },
    { ...wobbly, id: "external", display_name: "External mod", install_strategy: "External",
      release: { versions: [{ version: "1.2.3", published_at: "2026-09-02T00:00:00Z" }] } },
  ];
  const { site, readmePath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  const output = readFileSync(readmePath, "utf8");
  assert.ok(output.startsWith(`Handwritten introduction\n${begin}\n`));
  assert.ok(output.endsWith(`${end}\nHandwritten footer\n`));
  assert.ok(output.includes("| Game | Status | Supported stores | Links | Latest release |"));
  assert.ok(output.includes("| Wobbly Life | Beta | Steam, Xbox |"));
  assert.ok(output.includes("| Steam only | Beta | Steam |"));
  assert.ok(output.includes("| Store labels | Beta | GOG, Epic, Microsoft Store, EA app, Ubisoft Connect, Manual |"));
  assert.ok(output.includes("| Empty stores | Beta | Not specified |"));
  assert.ok(output.includes("| Absent stores | Beta | Not specified |"));
  assert.ok(output.includes("| External mod | Released | Steam, Xbox |"));
  assert.ok(!output.includes("Private mod"));
  for (const row of output.split("\n").filter(line => line.startsWith("|"))) {
    assert.equal(row.split("|").length, 7);
  }
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  assert.equal(readFileSync(readmePath, "utf8"), output);
});

test("README rejects an unknown store without changing the file", (t) => {
  const { site, readmePath } = workspace(t, [{ ...wobbly, verified_sources: ["Typo"] }]);
  const result = spawnSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")], { encoding: "utf8" });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /unknown verified source: Typo/);
  assert.equal(readFileSync(readmePath, "utf8"), readme);
});

for (const live of [false, true]) {
  test(`metadata refresh preserves Wobbly's stores and shared package (${live ? "live" : "full"})`, (t) => {
    const { root, site } = workspace(t, [wobbly]);
    const sourcePath = join(root, "lopari", "catalog", "mods.json");
    const originalSource = readFileSync(sourcePath, "utf8");
    const mock = join(root, "github.mjs");
    writeFileSync(mock, `
const release = ${JSON.stringify({
  name: "Development build 0.0.0-nightly.20260911.0a3073b", tag_name: "dev", prerelease: true,
  published_at: "2026-09-11T19:35:57Z",
  assets: [{ name: wobbly.distribution.pinned.zip_filename, browser_download_url: wobbly.distribution.pinned.download_url }],
})};
globalThis.fetch = async (url) => {
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases?per_page=25') return Response.json([release]);
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases/tags/dev') return Response.json(release);
  if (url === 'https://api.github.com/repos/itsloopyo/lopari-releases/releases/latest') return Response.json({tag_name: 'v0.8.3', assets: []});
  throw new Error('Unexpected fetch: ' + url);
};
`);
    execFileSync(process.execPath, ["--import", pathToFileURL(mock).href, join(site, "scripts", "update-metadata.mjs"), ...(live ? ["--live"] : [])], {
      env: { ...process.env, GITHUB_TOKEN: "test-only" },
    });
    const output = JSON.parse(readFileSync(join(site, "mods.json"), "utf8"));
    const updated = output.mods[0];
    assert.deepEqual(updated, {
      ...wobbly, distribution: { ...wobbly.distribution, pinned: {
        ...wobbly.distribution.pinned,
        version: "0.0.0-nightly.20260911.0a3073b", built_at: "2026-09-11T19:35:57Z",
      } },
    });
    assert.equal(output.schema_version, 2);
    if (live) assert.equal(readFileSync(sourcePath, "utf8"), originalSource);
    else assert.deepEqual(JSON.parse(readFileSync(sourcePath, "utf8")), output);
  });
}
