import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { test } from "node:test";

const scripts = dirname(fileURLToPath(import.meta.url));
const begin = "<!-- BEGIN MOD TABLE (generated by lopari.app: pixi run update-metadata) -->";
const end = "<!-- END MOD TABLE -->";
const recentBegin = "<!-- BEGIN NEW ADDITIONS (generated by lopari.app: pixi run update-metadata) -->";
const recentEnd = "<!-- END NEW ADDITIONS -->";
const daysAgo = (n) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
const recentList = (output) =>
  output.slice(output.indexOf(recentBegin) + recentBegin.length, output.indexOf(recentEnd)).trim();
const readme = `Handwritten introduction\n${recentBegin}\nold list\n${recentEnd}\nHandwritten middle\n${begin}\nold table\n${end}\nHandwritten footer\n`;
const wobbly = {
  id: "wobbly-life", display_name: "Wobbly Life", repo: "itsloopyo/wobbly-life-headtracking",
  public: true, released: false, added: "2026-05-28", install_strategy: "BepInEx5",
  verified_sources: ["Steam", "Xbox"],
  game: { steam_app_id: 1211020, executable_relpath: "Wobbly Life.exe" },
  known_issues: ["Not comprehensively tested."],
  distribution: { type: "dev-release", pinned: {
    version: "0.0.0-nightly.old", built_at: "2026-09-01T00:00:00Z",
    zip_filename: "WobblyLifeHeadTracking-dev-installer.zip",
    download_url: "https://github.com/itsloopyo/wobbly-life-headtracking/releases/download/dev/WobblyLifeHeadTracking-dev-installer.zip",
  } },
};

const staleRelease = {
  pinned: {
    version: "1.0.0", tag_name: "v1.0.0",
    zip_filename: "WobblyLifeHeadTracking-installer.zip",
    download_url: "https://github.com/itsloopyo/wobbly-life-headtracking/releases/download/v1.0.0/WobblyLifeHeadTracking-installer.zip",
  },
  versions: [{ version: "1.0.0", tag_name: "v1.0.0" }],
};

function workspace(t, mods) {
  const root = mkdtempSync(join(tmpdir(), "lopari-catalog-test-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const site = join(root, "lopari.app");
  mkdirSync(join(site, "scripts"), { recursive: true });
  mkdirSync(join(root, "lopari", "catalog"), { recursive: true });
  mkdirSync(join(root, "itsloopyo"));
  for (const script of ["update-metadata.mjs", "generate-readme.mjs", "generate-feed.mjs"]) {
    copyFileSync(join(scripts, script), join(site, "scripts", script));
  }
  const catalog = { schema_version: 2, mods, native_games: [] };
  writeFileSync(join(site, "mods.json"), JSON.stringify(catalog));
  writeFileSync(join(root, "lopari", "catalog", "mods.json"), JSON.stringify(catalog));
  writeFileSync(join(root, "itsloopyo", "README.md"), readme);
  return {
    root, site,
    readmePath: join(root, "itsloopyo", "README.md"),
    feedPath: join(site, "feed.xml"),
  };
}

test("README lists verified stores without inferring support from detection", (t) => {
  const mods = [
    wobbly,
    { ...wobbly, id: "steam", display_name: "Steam only", verified_sources: ["Steam"],
      game: { gog_ids: ["123"], xbox_paths: ["example"] } },
    { ...wobbly, id: "labels", display_name: "Store labels",
      verified_sources: ["Gog", "Epic", "Msix", "Ea", "Ubisoft", "Manual"] },
    { ...wobbly, id: "empty", display_name: "Empty stores", verified_sources: [] },
    { ...wobbly, id: "absent", display_name: "Absent stores", verified_sources: undefined },
    { ...wobbly, id: "private", display_name: "Private mod", public: false },
    { ...wobbly, id: "external", display_name: "External mod", install_strategy: "External",
      release: { versions: [{ version: "1.2.3", published_at: "2026-09-02T00:00:00Z" }] } },
  ];
  const { site, readmePath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  const output = readFileSync(readmePath, "utf8");
  assert.ok(output.startsWith(`Handwritten introduction\n${recentBegin}\n`));
  assert.ok(output.includes(`${recentEnd}\nHandwritten middle\n${begin}\n`));
  assert.ok(output.endsWith(`${end}\nHandwritten footer\n`));
  assert.ok(output.includes("| Game | Status | Supported stores | Links | Latest release |"));
  assert.ok(output.includes("| Wobbly Life | Beta | Steam, Xbox |"));
  assert.ok(output.includes("| Steam only | Beta | Steam |"));
  assert.ok(output.includes("| Store labels | Beta | GOG, Epic, Microsoft Store, EA app, Ubisoft Connect, Manual |"));
  assert.ok(output.includes("| Empty stores | Beta | Not specified |"));
  assert.ok(output.includes("| Absent stores | Beta | Not specified |"));
  assert.ok(output.includes("| External mod | Released | Steam, Xbox |"));
  assert.ok(!output.includes("Private mod"));
  for (const row of output.split("\n").filter(line => line.startsWith("|"))) {
    assert.equal(row.split("|").length, 7);
  }
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  assert.equal(readFileSync(readmePath, "utf8"), output);
});

test("README lists every mod added this week, newest first", (t) => {
  const mods = [
    { ...wobbly, id: "today", display_name: "Today", added: daysAgo(0) },
    { ...wobbly, id: "same-day", display_name: "Also today", added: daysAgo(0) },
    { ...wobbly, id: "edge", display_name: "Six days", added: daysAgo(6) },
    { ...wobbly, id: "old", display_name: "Seven days", added: daysAgo(7) },
    { ...wobbly, id: "private", display_name: "Private mod", public: false, added: daysAgo(1) },
  ];
  const { site, readmePath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  const repo = "[GitHub](https://github.com/itsloopyo/wobbly-life-headtracking)";
  assert.deepEqual(recentList(readFileSync(readmePath, "utf8")).split("\n"), [
    `- **Also today** (Beta), added ${daysAgo(0)} · ${repo}`,
    `- **Today** (Beta), added ${daysAgo(0)} · ${repo}`,
    `- **Six days** (Beta), added ${daysAgo(6)} · ${repo}`,
  ]);
});

test("README says so when nothing was added this week", (t) => {
  const { site, readmePath } = workspace(t, [{ ...wobbly, added: daysAgo(7) }]);
  execFileSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")]);
  assert.equal(recentList(readFileSync(readmePath, "utf8")), "No new mods this week.");
});

test("README and feed refuse a public mod with no added date", (t) => {
  const { added: _, ...undated } = wobbly;
  const { site, readmePath, feedPath } = workspace(t, [undated]);
  for (const script of ["generate-readme.mjs", "generate-feed.mjs"]) {
    const result = spawnSync(process.execPath, [join(site, "scripts", script)], { encoding: "utf8" });
    assert.equal(result.status, 1, script);
    assert.match(result.stderr, /wobbly-life is public with no "added" date/);
  }
  assert.equal(readFileSync(readmePath, "utf8"), readme);
  assert.ok(!existsSync(feedPath));
});

test("feed lists public mods newest first and is stable across runs", (t) => {
  const mods = [
    wobbly,
    { ...wobbly, id: "newer", display_name: "Tom & Jerry <Deluxe>", added: "2026-09-19",
      description: "Works with any OpenTrack compatible tracker." },
    { ...wobbly, id: "private", display_name: "Private mod", public: false, added: "2026-09-30" },
  ];
  const { site, feedPath } = workspace(t, mods);
  execFileSync(process.execPath, [join(site, "scripts", "generate-feed.mjs")]);
  const feed = readFileSync(feedPath, "utf8");
  assert.ok(feed.includes("<updated>2026-09-19T00:00:00Z</updated>\n  <entry>"));
  assert.ok(feed.indexOf("mod/newer") < feed.indexOf("mod/wobbly-life"));
  assert.ok(feed.includes("<title>Tom &amp; Jerry &lt;Deluxe&gt;</title>"));
  assert.ok(feed.includes("<summary>Works with any OpenTrack compatible tracker.</summary>"));
  assert.ok(feed.includes("<published>2026-05-28T00:00:00Z</published>"));
  assert.ok(!feed.includes("Private mod"));
  assert.equal(feed.match(/<entry>/g).length, 2);
  execFileSync(process.execPath, [join(site, "scripts", "generate-feed.mjs")]);
  assert.equal(readFileSync(feedPath, "utf8"), feed);
});

test("README rejects an unknown store without changing the file", (t) => {
  const { site, readmePath } = workspace(t, [{ ...wobbly, verified_sources: ["Typo"] }]);
  const result = spawnSync(process.execPath, [join(site, "scripts", "generate-readme.mjs")], { encoding: "utf8" });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /unknown verified source: Typo/);
  assert.equal(readFileSync(readmePath, "utf8"), readme);
});

for (const live of [false, true]) {
  for (const scenario of [
    { name: "drops a stale release on an unstamped entry", released: false, dev: "available", dropRelease: true, status: 0 },
    { name: "drops a stale release and unstamps an entry with a dev build", released: true, dev: "available", dropRelease: true, status: 0 },
    { name: "preserves a stale release and errors without a dev channel", released: true, dev: "none", status: 1 },
    { name: "preserves a stale release and errors when the dev release is missing", released: true, dev: "missing", status: 1 },
    { name: "preserves a stale release and errors when the dev installer is missing", released: true, dev: "assetless", status: 1 },
    { name: "preserves the stable release and stamp on a GitHub failure", released: true, dev: "available", releaseFailure: true, status: 1 },
  ]) {
    test(`metadata refresh ${scenario.name} (${live ? "live" : "full"})`, (t) => {
      const mod = { ...wobbly, released: scenario.released, release: staleRelease };
      if (scenario.dev === "none") delete mod.distribution;
      const expected = structuredClone(mod);
      if (scenario.dropRelease) {
        delete expected.release;
        expected.released = false;
      }
      if (["missing", "assetless"].includes(scenario.dev)) delete expected.distribution.pinned;
      const { root, site } = workspace(t, [mod]);
      const sourcePath = join(root, "lopari", "catalog", "mods.json");
      const originalSource = readFileSync(sourcePath, "utf8");
      const mock = join(root, "github.mjs");
      writeFileSync(mock, `
const scenario = ${JSON.stringify(scenario)};
const pin = ${JSON.stringify(wobbly.distribution.pinned)};
globalThis.fetch = async (url) => {
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases?per_page=25') {
    return scenario.releaseFailure
      ? new Response('unavailable', { status: 503, statusText: 'Service Unavailable' })
      : Response.json([]);
  }
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases/tags/dev' && scenario.dev !== 'none') {
    if (scenario.dev === 'missing') return new Response(null, { status: 404 });
    return Response.json({
      name: 'Development build ' + pin.version, tag_name: 'dev', prerelease: true,
      published_at: pin.built_at,
      assets: scenario.dev === 'assetless' ? [] : [{ name: pin.zip_filename, browser_download_url: pin.download_url }],
    });
  }
  if (url === 'https://api.github.com/repos/itsloopyo/lopari-releases/releases/latest') return Response.json({tag_name: 'v0.8.3', assets: []});
  throw new Error('Unexpected fetch: ' + url);
};
`);
      const result = spawnSync(process.execPath, ["--import", pathToFileURL(mock).href, join(site, "scripts", "update-metadata.mjs"), ...(live ? ["--live"] : [])], {
        encoding: "utf8", env: { ...process.env, GITHUB_TOKEN: "test-only" },
      });
      assert.equal(result.status, scenario.status, result.stdout + result.stderr);
      if (scenario.releaseFailure) {
        assert.match(result.stderr, /GET https:\/\/api\.github\.com\/repos\/itsloopyo\/wobbly-life-headtracking\/releases\?per_page=25 -> 503 Service Unavailable/);
        assert.doesNotMatch(result.stderr, /has no dev build to fall back on/);
      } else if (scenario.status === 1) {
        assert.match(result.stderr, /has no dev build to fall back on\. Restore the release, or hand-edit the entry in the lopari catalog/);
      } else {
        assert.equal(result.stderr, "");
      }
      const output = JSON.parse(readFileSync(join(site, "mods.json"), "utf8"));
      assert.deepEqual(output.mods, [expected]);
      if (live) assert.equal(readFileSync(sourcePath, "utf8"), originalSource);
      else assert.deepEqual(JSON.parse(readFileSync(sourcePath, "utf8")), output);
    });
  }

  test(`metadata refresh preserves Wobbly's stores and shared package (${live ? "live" : "full"})`, (t) => {
    const { root, site } = workspace(t, [wobbly]);
    const sourcePath = join(root, "lopari", "catalog", "mods.json");
    const originalSource = readFileSync(sourcePath, "utf8");
    const mock = join(root, "github.mjs");
    writeFileSync(mock, `
const release = ${JSON.stringify({
  name: "Development build 0.0.0-nightly.20260911.0a3073b", tag_name: "dev", prerelease: true,
  published_at: "2026-09-11T19:35:57Z",
  assets: [{ name: wobbly.distribution.pinned.zip_filename, browser_download_url: wobbly.distribution.pinned.download_url }],
})};
globalThis.fetch = async (url) => {
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases?per_page=25') return Response.json([release]);
  if (url === 'https://api.github.com/repos/itsloopyo/wobbly-life-headtracking/releases/tags/dev') return Response.json(release);
  if (url === 'https://api.github.com/repos/itsloopyo/lopari-releases/releases/latest') return Response.json({tag_name: 'v0.8.3', assets: []});
  throw new Error('Unexpected fetch: ' + url);
};
`);
    execFileSync(process.execPath, ["--import", pathToFileURL(mock).href, join(site, "scripts", "update-metadata.mjs"), ...(live ? ["--live"] : [])], {
      env: { ...process.env, GITHUB_TOKEN: "test-only" },
    });
    const output = JSON.parse(readFileSync(join(site, "mods.json"), "utf8"));
    const updated = output.mods[0];
    assert.deepEqual(updated, {
      ...wobbly, distribution: { ...wobbly.distribution, pinned: {
        ...wobbly.distribution.pinned,
        version: "0.0.0-nightly.20260911.0a3073b", built_at: "2026-09-11T19:35:57Z",
      } },
    });
    assert.equal(output.schema_version, 2);
    if (live) assert.equal(readFileSync(sourcePath, "utf8"), originalSource);
    else assert.deepEqual(JSON.parse(readFileSync(sourcePath, "utf8")), output);
  });
}
