// Runs after `node scripts/update-metadata.mjs` (see pixi.toml).
//
// Rewrites the mod table in ../itsloopyo/README.md - the itsloopyo GitHub
// profile README - from the catalog, so the public list of mods can't drift
// from what the launcher ships. Every column is derived:
//
//   Game            display_name
//   Status          Released (has a stable release) / Beta (dev builds only)
//   Supported stores verified_sources
//   Links           the repo, plus any `listings` (NexusMods, Overtake.gg)
//   Latest release  the pinned stable version, or "dev build" for a Beta,
//                   with the date it was published
//
// It writes the public mod count between an inline pair of markers in the
// hand-written intro. Between a second pair of markers it lists the
// LIST_LENGTH newest arrivals: a mod on the day it was `added`, and a mod
// again for each store in its `source_added`, worded as support for that
// store so a platform release does not read as a new game. Between a third
// pair it lists the LIST_LENGTH mods outside that list whose latest build
// (the one the table shows) is most recent.
// A build dated the day its mod was added is the launch, not an update, so
// it stays out of that list. update-pins.yml moves the pins in the live
// mods.json hourly, so the profile repo's nightly refresh-readme workflow
// reruns this to keep the updates list current.
//
// Reads THIS repo's mods.json, not ../lopari/catalog/mods.json: the Pages
// copy is already filtered to public mods, which is exactly what belongs on
// a public profile, and it keeps the generator runnable without the private
// lopari checkout. update-metadata.mjs writes it immediately before this
// runs, so it is never the stale copy.
//
// Only the regions between the BEGIN/END markers are touched - the prose
// around the table is hand-written and stays that way.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CATALOG_PATH = resolve(REPO_ROOT, "mods.json");
const README_PATH = resolve(REPO_ROOT, "..", "itsloopyo", "README.md");

const BEGIN = "<!-- BEGIN MOD TABLE (generated by lopari.app: pixi run update-metadata) -->";
const END = "<!-- END MOD TABLE -->";
const RECENT_BEGIN = "<!-- BEGIN NEW ADDITIONS (generated by lopari.app: pixi run update-metadata) -->";
const RECENT_END = "<!-- END NEW ADDITIONS -->";
const COUNT_BEGIN = "<!-- BEGIN MOD COUNT -->";
const COUNT_END = "<!-- END MOD COUNT -->";
const UPDATED_BEGIN = "<!-- BEGIN RECENT UPDATES (generated by lopari.app: pixi run update-metadata) -->";
const UPDATED_END = "<!-- END RECENT UPDATES -->";
const LIST_LENGTH = 10;
const STORE_LABELS = {
  Steam: "Steam", Gog: "GOG", Epic: "Epic", Xbox: "Xbox",
  Msix: "Microsoft Store", Ea: "EA app", Ubisoft: "Ubisoft Connect", Manual: "Retail",
};

function storeLabel(mod, source) {
  if (!Object.hasOwn(STORE_LABELS, source)) {
    throw new Error(`${mod.id} has an unknown verified source: ${source}`);
  }
  return STORE_LABELS[source];
}

// A mod with a stable release is Released whatever `released` says: that
// flag means "the launcher installs the stable channel", which External
// mods never do even once they ship stable builds.
function stableChannel(mod) {
  const versions = mod.release ? mod.release.versions : null;
  if (mod.release && mod.release.pinned) return mod.release.pinned;
  if (versions && versions.length > 0) return versions[0];
  return null;
}

function latestRelease(mod) {
  const stable = stableChannel(mod);
  if (stable) {
    return { status: "Released", version: stable.version, date: stable.published_at };
  }
  if (mod.released === true) {
    throw new Error(
      `${mod.id} is released: true but carries no release pin - re-run update-metadata`,
    );
  }
  const dev = mod.distribution ? mod.distribution.pinned : null;
  if (!dev) {
    throw new Error(
      `${mod.id} is public with neither a stable release nor a pinned dev build - nothing to list`,
    );
  }
  return { status: "Beta", version: null, date: dev.built_at };
}

function links(mod) {
  const all = [{ name: "GitHub", url: `https://github.com/${mod.repo}` }, ...(mod.listings ?? [])];
  return all.map((l) => `[${l.name}](${l.url})`).join(" · ");
}

function row(mod) {
  const { status, version, date } = latestRelease(mod);
  if (!date) throw new Error(`${mod.id} has a release with no date to show`);
  const stores = (mod.verified_sources ?? [])
    .map((source) => storeLabel(mod, source))
    .join(", ") || "Not specified";
  const build = version ? `v${version}` : "dev build";
  return `| ${mod.display_name} | ${status} | ${stores} | ${links(mod)} | ${build} (${date.slice(0, 10)}) |`;
}

function replaceBetween(text, begin, end, body, separator = "\n\n") {
  const start = text.indexOf(begin);
  const stop = text.indexOf(end);
  if (start === -1 || stop === -1) {
    throw new Error(`${README_PATH} is missing the ${begin} / ${end} markers`);
  }
  return text.slice(0, start + begin.length) + separator + body + separator + text.slice(stop);
}

const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));
const mods = catalog.mods
  .filter((m) => m.public === true)
  .sort((a, b) => a.display_name.localeCompare(b.display_name, "en", { sensitivity: "base" }));

const table = [
  "| Game | Status | Supported stores | Links | Latest release |",
  "|---|---|---|---|---|",
  ...mods.map(row),
].join("\n");

for (const m of mods) {
  if (!m.added) throw new Error(`${m.id} is public with no "added" date - set it in the lopari catalog`);
}
// mods is already in name order and the sorts are stable, so ties stay alphabetical.
const arrivals = mods
  .flatMap((m) => [
    { mod: m, date: m.added, what: "added" },
    ...Object.entries(m.source_added ?? {}).map(([source, date]) => (
      { mod: m, date, what: `${storeLabel(m, source)} support added` }
    )),
  ])
  .sort((a, b) => b.date.localeCompare(a.date))
  .slice(0, LIST_LENGTH);
const recent = arrivals
  .map(({ mod, date, what }) =>
    `- **${mod.display_name}** (${latestRelease(mod).status}), ${what} ${date} · [GitHub](https://github.com/${mod.repo})`)
  .join("\n");

const updatedMods = mods
  .filter((m) => !arrivals.some((a) => a.mod === m))
  .map((m) => ({ mod: m, build: latestRelease(m) }))
  .filter(({ mod, build }) => build.date.slice(0, 10) > mod.added)
  .sort((a, b) => b.build.date.localeCompare(a.build.date))
  .slice(0, LIST_LENGTH);
const updates = updatedMods.length === 0
  ? "No updates yet."
  : updatedMods
    .map(({ mod, build }) =>
      `- **${mod.display_name}** (${build.status}), ${build.version ? `v${build.version}` : "dev build"} on ${build.date.slice(0, 10)} · [GitHub](https://github.com/${mod.repo})`)
    .join("\n");

const readme = readFileSync(README_PATH, "utf8");
let updated = replaceBetween(readme, COUNT_BEGIN, COUNT_END, String(mods.length), "");
updated = replaceBetween(updated, RECENT_BEGIN, RECENT_END, recent);
updated = replaceBetween(updated, UPDATED_BEGIN, UPDATED_END, updates);
updated = replaceBetween(updated, BEGIN, END, table);
if (updated === readme) {
  console.log(`README unchanged (${mods.length} mods)`);
} else {
  writeFileSync(README_PATH, updated, "utf8");
  const released = mods.filter((m) => stableChannel(m)).length;
  console.log(
    `wrote ${README_PATH}\nmods: ${mods.length} (${released} released, ${mods.length - released} beta)`,
  );
}
