// Runs after `node scripts/update-metadata.mjs` (see pixi.toml).
//
// Rewrites the mod table in ../itsloopyo/README.md - the itsloopyo GitHub
// profile README - from the catalog, so the public list of mods can't drift
// from what the launcher ships. Every column is derived:
//
//   Game            display_name
//   Status          Released (has a stable release) / Beta (dev builds only)
//   Links           the repo, plus any `listings` (NexusMods, Overtake.gg)
//   Latest release  the pinned stable version, or the dev build's base
//                   version, with the date it was published
//
// Reads THIS repo's mods.json, not ../lopari/catalog/mods.json: the Pages
// copy is already filtered to public mods, which is exactly what belongs on
// a public profile, and it keeps the generator runnable without the private
// lopari checkout. update-metadata.mjs writes it immediately before this
// runs, so it is never the stale copy.
//
// Only the region between the BEGIN/END markers is touched - the prose
// around the table is hand-written and stays that way.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CATALOG_PATH = resolve(REPO_ROOT, "mods.json");
const README_PATH = resolve(REPO_ROOT, "..", "itsloopyo", "README.md");

const BEGIN = "<!-- BEGIN MOD TABLE (generated by lopari.app: pixi run update-metadata) -->";
const END = "<!-- END MOD TABLE -->";

// A mod with a stable release is Released whatever `released` says: that
// flag means "the launcher installs the stable channel", which External
// mods never do even once they ship stable builds.
function stableChannel(mod) {
  const versions = mod.release ? mod.release.versions : null;
  if (mod.release && mod.release.pinned) return mod.release.pinned;
  if (versions && versions.length > 0) return versions[0];
  return null;
}

function latestRelease(mod) {
  const stable = stableChannel(mod);
  if (stable) {
    return { status: "Released", version: stable.version, date: stable.published_at };
  }
  if (mod.released === true) {
    throw new Error(
      `${mod.id} is released: true but carries no release pin - re-run update-metadata`,
    );
  }
  const dev = mod.distribution ? mod.distribution.pinned : null;
  if (!dev) {
    throw new Error(
      `${mod.id} is public with neither a stable release nor a pinned dev build - nothing to list`,
    );
  }
  // Dev versions are "<base>-nightly.<date>.<sha>"; the base is the version
  // the mod is working towards, which is what the table shows.
  return { status: "Beta", version: dev.version.split("-nightly")[0], date: dev.built_at };
}

function links(mod) {
  const all = [{ name: "GitHub", url: `https://github.com/${mod.repo}` }, ...(mod.listings ?? [])];
  return all.map((l) => `[${l.name}](${l.url})`).join(" · ");
}

function row(mod) {
  const { status, version, date } = latestRelease(mod);
  if (!date) throw new Error(`${mod.id} has a release with no date to show`);
  return `| ${mod.display_name} | ${status} | ${links(mod)} | v${version} (${date.slice(0, 10)}) |`;
}

const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));
const mods = catalog.mods
  .filter((m) => m.public === true)
  .sort((a, b) => a.display_name.localeCompare(b.display_name, "en", { sensitivity: "base" }));

const table = [
  "| Game | Status | Links | Latest release |",
  "|---|---|---|---|",
  ...mods.map(row),
].join("\n");

const readme = readFileSync(README_PATH, "utf8");
const start = readme.indexOf(BEGIN);
const end = readme.indexOf(END);
if (start === -1 || end === -1) {
  throw new Error(`${README_PATH} is missing the ${BEGIN} / ${END} markers`);
}

const updated =
  readme.slice(0, start + BEGIN.length) + "\n\n" + table + "\n\n" + readme.slice(end);
if (updated === readme) {
  console.log(`README table unchanged (${mods.length} mods)`);
} else {
  writeFileSync(README_PATH, updated, "utf8");
  const released = mods.filter((m) => stableChannel(m)).length;
  console.log(
    `wrote ${README_PATH}\nmods: ${mods.length} (${released} released, ${mods.length - released} beta)`,
  );
}
