// Runs after `node scripts/update-metadata.mjs` (see pixi.toml).
//
// Rewrites the mod table in ../itsloopyo/README.md - the itsloopyo GitHub
// profile README - from the catalog, so the public list of mods can't drift
// from what the launcher ships. Every column is derived:
//
//   Game            display_name
//   Status          Released (has a stable release) / Beta (dev builds only)
//   Supported stores verified_sources
//   Links           the repo, plus any `listings` (NexusMods, Overtake.gg)
//   Latest release  the pinned stable version, or the dev build's base
//                   version, with the date it was published
//
// It also lists, between a second pair of markers, every mod `added` in
// the RECENT_DAYS up to and including the day it runs, newest first. The
// window only moves when this runs, which the profile repo's nightly
// refresh-readme workflow does.
//
// Reads THIS repo's mods.json, not ../lopari/catalog/mods.json: the Pages
// copy is already filtered to public mods, which is exactly what belongs on
// a public profile, and it keeps the generator runnable without the private
// lopari checkout. update-metadata.mjs writes it immediately before this
// runs, so it is never the stale copy.
//
// Only the regions between the BEGIN/END markers are touched - the prose
// around the table is hand-written and stays that way.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CATALOG_PATH = resolve(REPO_ROOT, "mods.json");
const README_PATH = resolve(REPO_ROOT, "..", "itsloopyo", "README.md");

const BEGIN = "<!-- BEGIN MOD TABLE (generated by lopari.app: pixi run update-metadata) -->";
const END = "<!-- END MOD TABLE -->";
const RECENT_BEGIN = "<!-- BEGIN NEW ADDITIONS (generated by lopari.app: pixi run update-metadata) -->";
const RECENT_END = "<!-- END NEW ADDITIONS -->";
const RECENT_DAYS = 7;

// A mod with a stable release is Released whatever `released` says: that
// flag means "the launcher installs the stable channel", which External
// mods never do even once they ship stable builds.
function stableChannel(mod) {
  const versions = mod.release ? mod.release.versions : null;
  if (mod.release && mod.release.pinned) return mod.release.pinned;
  if (versions && versions.length > 0) return versions[0];
  return null;
}

function latestRelease(mod) {
  const stable = stableChannel(mod);
  if (stable) {
    return { status: "Released", version: stable.version, date: stable.published_at };
  }
  if (mod.released === true) {
    throw new Error(
      `${mod.id} is released: true but carries no release pin - re-run update-metadata`,
    );
  }
  const dev = mod.distribution ? mod.distribution.pinned : null;
  if (!dev) {
    throw new Error(
      `${mod.id} is public with neither a stable release nor a pinned dev build - nothing to list`,
    );
  }
  // Dev versions are "<base>-nightly.<date>.<sha>"; the base is the version
  // the mod is working towards, which is what the table shows.
  return { status: "Beta", version: dev.version.split("-nightly")[0], date: dev.built_at };
}

function links(mod) {
  const all = [{ name: "GitHub", url: `https://github.com/${mod.repo}` }, ...(mod.listings ?? [])];
  return all.map((l) => `[${l.name}](${l.url})`).join(" · ");
}

function row(mod) {
  const { status, version, date } = latestRelease(mod);
  if (!date) throw new Error(`${mod.id} has a release with no date to show`);
  const labels = {
    Steam: "Steam", Gog: "GOG", Epic: "Epic", Xbox: "Xbox",
    Msix: "Microsoft Store", Ea: "EA app", Ubisoft: "Ubisoft Connect", Manual: "Manual",
  };
  const stores = (mod.verified_sources ?? []).map((source) => {
    if (!Object.hasOwn(labels, source)) {
      throw new Error(`${mod.id} has an unknown verified source: ${source}`);
    }
    return labels[source];
  }).join(", ") || "Not specified";
  return `| ${mod.display_name} | ${status} | ${stores} | ${links(mod)} | v${version} (${date.slice(0, 10)}) |`;
}

function replaceBetween(text, begin, end, body) {
  const start = text.indexOf(begin);
  const stop = text.indexOf(end);
  if (start === -1 || stop === -1) {
    throw new Error(`${README_PATH} is missing the ${begin} / ${end} markers`);
  }
  return text.slice(0, start + begin.length) + "\n\n" + body + "\n\n" + text.slice(stop);
}

const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));
const mods = catalog.mods
  .filter((m) => m.public === true)
  .sort((a, b) => a.display_name.localeCompare(b.display_name, "en", { sensitivity: "base" }));

const table = [
  "| Game | Status | Supported stores | Links | Latest release |",
  "|---|---|---|---|---|",
  ...mods.map(row),
].join("\n");

for (const m of mods) {
  if (!m.added) throw new Error(`${m.id} is public with no "added" date - set it in the lopari catalog`);
}
const since = new Date(Date.now() - (RECENT_DAYS - 1) * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
const recentMods = mods
  .filter((m) => m.added >= since)
  .sort((a, b) =>
    b.added.localeCompare(a.added) ||
    a.display_name.localeCompare(b.display_name, "en", { sensitivity: "base" }));
const recent = recentMods.length === 0
  ? "No new mods this week."
  : recentMods
    .map((m) => `- **${m.display_name}** (${latestRelease(m).status}), added ${m.added} · [GitHub](https://github.com/${m.repo})`)
    .join("\n");

const readme = readFileSync(README_PATH, "utf8");
const updated = replaceBetween(
  replaceBetween(readme, RECENT_BEGIN, RECENT_END, recent),
  BEGIN,
  END,
  table,
);
if (updated === readme) {
  console.log(`README unchanged (${mods.length} mods)`);
} else {
  writeFileSync(README_PATH, updated, "utf8");
  const released = mods.filter((m) => stableChannel(m)).length;
  console.log(
    `wrote ${README_PATH}\nmods: ${mods.length} (${released} released, ${mods.length - released} beta)`,
  );
}
